# High-level project configuration
project:
  name: "ids_svm_dt"
  seed: 42
  dataset: "NSL-KDD"

paths:
  raw_dir: "data/raw"
  interim_dir: "data/interim"
  processed_dir: "data/processed"
  models_dir: "models"
  reports_dir: "reports/metrics"

# Task type: binary (normal vs attack) or multiclass (families)
training:
  task: "binary"
  test_size: 0.2  # only used if you choose to re-split; by default we use official KDDTest+
  fast_rows: 40000  # subset rows for faster SVM prototyping

svm:
  C: [1, 3]
  gamma: ["scale"]
  cv: 3
  class_weight: "balanced"
  probability: true

decision_tree:
  max_depth: [null, 20, 40]
  min_samples_split: [2, 10, 50]
  min_samples_leaf: [1, 5, 10]
  cv: 3
  class_weight: "balanced"
